### ISSUE TITLE
Not much of a issue but just asking for ya to update it for the new cards since the full version of Kaycee's mod got released yesterday

### ISSUE THREAD

**Issue by Mariotron1** [jlcrochet/inscryption_save_editor#1]

**Comment by jlcrochet** [comment]
All of the cards released throughout the KMod beta are already in. Unless the full version added even more cards that I'm not aware of, there shouldn't be any reason to update. If you find any cards while playing that aren't in, please reopen this issue.

**Comment by Mariotron1** [comment]
The Flying ant

**Comment by jlcrochet** [comment]
You're right, thanks for catching that. The Flying Ant should be in now.
