### ISSUE TITLE
Act 3 energy modification not working?

### ISSUE THREAD

**Issue by c0rnography** [jlcrochet/inscryption_save_editor#11]
For some reason in Act 3 when I try to edit the energy a card requires, it won't change in-game. The naming works and the sigils work, but I can't seem to mess with the energy. (This has been really fun to fuck with so far to see how far I can push the game, though, nice work, dude)

**Comment by jlcrochet** [comment]
That's weird, it works for me. Did you make sure to give it a negative number? For example, setting the energy adjustment on a modification to -3 will decrease the energy cost of the card by 3; setting it to 3 will _increase_ the energy cost by 3. If that doesn't work, maybe you can give me a copy of your save file and tell me which card you tried to edit.

**Comment by c0rnography** [comment]
Okay, that was totally user error, then. To be honest, I have no idea how I didn’t realize that. I was trying to test out using just one overpowered card, so I didn’t realize it was attempting to add cost— It already required full energy. Sorry about that, dude. 

Also, wanna say that I tried out using blood in act 3 because it led me to try new things as well, and I’m surprised and really happy that it (kind of) worked haha.

**Comment by jlcrochet** [comment]
Yeah, a lot of the differences between the acts are merely cosmetic. For example, you can use Act 1 items in Act 3 or vice versa.
