### ISSUE TITLE
setTab update breaks save editor

### ISSUE THREAD

**Issue by TheDemitrius** [jlcrochet/inscryption_save_editor#13]
"ReferenceError: tabIndex is not defined" when attempting to change tabs.

I believe commit cc8dac3f77b341df1b6f2d4cb5fd31790fd7771f is the culprit here, as it changes how tabs are changed - namely implementing the use of a setTab method, where this error is originating.

**Comment by jlcrochet** [comment]
Sorry, I forgot how to JavaScript. It should be working now.
