### ISSUE TITLE
Unable to click any of the tabs on the Save Editor. [Save Attached]

### ISSUE THREAD

**Issue by NicoTheCinderace** [jlcrochet/inscryption_save_editor#14]
What's odd is that it worked fine the other day, but just randomly decided to break now, after completing the painting puzzle.

[I've attached my Save File. This is just a weird error that's preventing me from clicking on any of the buttons. Act Two through Four and the Kaycee's Mod button are non-functional for whatever reason. Any help would be appreciated, thanks.](https://github.com/jlcrochet/inscryption_save_editor/files/9227772/SaveFile.zip)

**Comment by jlcrochet** [comment]
Okay, this should be fixed now. Apparently, I was using the wrong internal name for the Wild Bull card.

**Comment by NicoTheCinderace** [comment]
Thanks, this indeed fixed it. I appreciate the quick response time. :)
