### ISSUE TITLE
Unable to click any of the tabs on the Save Editor.

### ISSUE THREAD

**Issue by Jiyuuneko** [jlcrochet/inscryption_save_editor#15]
I am facing the same problem like #14 after I beat The Archivist of ACT 3 .
Here is my save file.
[SaveFile.zip](https://github.com/jlcrochet/inscryption_save_editor/files/9487408/SaveFile.zip)

**Comment by jlcrochet** [comment]
Sorry, this was due to a typo on my part. This should be fixed now.

**Comment by GattoLand** [comment]
Thanks for your time, it actually worked.
