### ISSUE TITLE
Can't load my save file.

### ISSUE THREAD

**Issue by LimonluMentozDev** [jlcrochet/inscryption_save_editor#16]
![resim_2022-10-20_200137557](https://user-images.githubusercontent.com/116300124/197012601-f594b468-9689-4f85-9d57-577ccb950866.png)
It gets stuck at "Loading..."
Issue has been occuring for a few weeks now.

Made an github account just for this, dunno how to github.

**Comment by jlcrochet** [comment]
Could you upload your save file so that I can test it myself?

**Comment by LimonluMentozDev** [comment]
Sadly Github doesn't support uploading .gwsave files. I uploaded them on my google drive so you can download it there. https://drive.google.com/file/d/16FrcmRHNTxp33kb8Ke_-WiEDcEcHDQpc

**Comment by LimonluMentozDev** [comment]
Hi, I just updated my game and it works again, thanks.
