### ISSUE TITLE
Save files from skyline emulator cannot parse?

### ISSUE THREAD

**Issue by ghost** [jlcrochet/inscryption_save_editor#17]
I have a save file that doesn't parse for some strange reason. here is a link.[](https://anonymfile.com/pdzaJ/010027f017b12000.zip)

**Comment by jlcrochet** [comment]
I don't see a link in your comment. If you can't upload the file here, you can e-mail it to me if you like.

**Comment by joemck** [comment]
I'm AlexS2412's friend and I solved their problem. They had raw OptionsData.json and SaveFile.gwsave ripped from the Skyline Switch emulator rather than extracted using Checkpoint or EdiZon since Skyline apparently can't run those. It's the same files that are encoded as JSON in save.fs, but the editor wouldn't load them because they have a binary header and a single character tacked on at the end. After chopping the binary off it, the editor loads the Skyline SaveFile.gwsave, and after encoding OptionsData.json and SaveFile.gwsave as JSON byte arrays, the editor loads it as save.fs and Checkpoint/EdiZon are able to restore it on a real Switch as well.

I've also attached the save data in question in case you want to add support for raw Switch data files not encoded into save.fs since Skyline is the only viable Switch emulator on Android right now and as far as I know it can't export the save in either way that the editor wants it.

[010027F017B12000.zip](https://github.com/jlcrochet/inscryption_save_editor/files/10977854/010027F017B12000.zip)

**Comment by jlcrochet** [comment]
I've updated the editor to accept plain Switch save files like the one in the attachment. It should now properly strip the header bytes before editing the input file and write a new header in the output file that the Switch version of the game should be able to read. I don't have a copy of the Switch version to test with, so if you guys could test it out at some point and let me know if it works, that would be great.

**Comment by ghost** [comment]
> I've updated the editor to accept plain Switch save files like the one in the attachment. It should now properly strip the header bytes before editing the input file and write a new header in the output file that the Switch version of the game should be able to read. I don't have a copy of the Switch version to test with, so if you guys could test it out at some point and let me know if it works, that would be great.

can we have option to convert between gwsave and fa formats? as of rn it's not possible to turn a real switch fs save back into gwsave

**Comment by jlcrochet** [comment]
I've added the ability to specify the output format from a dropdown menu next to the Save button; this should allow you to edit a file in one format, then produce a file in whatever format you choose.

There are currently three output formats:

* `.gwsave (PC)`: JSON only
* `.gwsave (Nintendo Switch)`: Header bytes + JSON + trailing vertical tab; should be compatible with Nintendo Switch filesystem
* `.fs (Checkpoint)`: This should produce output that can be restored using Checkpoint or something similar

The default output format will be detected from the input file.

As usual, any testing on this is appreciated.

**Comment by ghost** [comment]
sadly it doesn't seem to work. it says the save is corrupt, and interestingly says to rervert to a backup inside the switch version of the game. is there a way we could chat more directly about the issue? i feel like its a small one and i mainly use matrix to talk, or telegram if you have either.

**Comment by ghost** [comment]
@jlcrochet so it seems your parser cant convert them back once they are turned into switch gwsave, and in fact makes it unreadable by the game itself too, failed conversion perhaps?

**Comment by jlcrochet** [comment]
If possible, could you give me the most recent save file that you've tried?

**Comment by ghost** [comment]
sure thing. on mobile github doesnt let me upload them, so i have to zip it. here is the current saves i am working with. https://file.io/zh3pbMkIP1xF

**Comment by ghost** [comment]
> If possible, could you give me the most recent save file that you've tried?

@jlcrochet just in case you missed it https://www.filemail.com/d/cjnlsatfjtwslwk

**Comment by joemck** [comment]
When converting a save.fs into a Switch SaveFile.gwsave, it appears to be outputting UTF-8 codepoint 00FF (C3 BF) in the header when the save.fs says 255. Even when I manually translate the header though, it still won't load in the game.

**Comment by ghost** [comment]
@jlcrochet here is simple python tools that correctly swap the save data. these were made by @joemck [Tool](https://www.filemail.com/d/exgkgqebhufnxwk)

**Comment by jlcrochet** [comment]
It's possible that it was an encoding issue, since JavaScript strings use UTF-16 by default. I've made some changes to use raw bytes as much as possible. The output files look the same according to my testing, but it could be that the Switch will handle them better.

**Comment by jlcrochet** [comment]
As an example, when I take the .fs file that you gave me yesterday, load it into the editor, save it as a .gwsave in Nintendo Switch format, then look at the first few lines of the hexdump:

```
00000000  00 01 00 00 00 ff ff ff  ff 01 00 00 00 00 00 00  |................|
00000010  00 06 01 00 00 00 aa d2  14 7b 22 24 69 64 22 3a  |.........{"$id":|
00000020  30 2c 22 24 74 79 70 65  22 3a 22 53 61 76 65 46  |0,"$type":"SaveF|
00000030  69 6c 65 2c 20 41 73 73  65 6d 62 6c 79 2d 43 53  |ile, Assembly-CS|
...
```

Looks like the header bytes should be correct now.

**Comment by ghost** [comment]
everything seems to work! :)
