### ISSUE TITLE
Error Parsing File

### ISSUE THREAD

**Issue by JPW62490** [jlcrochet/inscryption_save_editor#18]
I loaded the file as usual, but it triggered the error message. File should be up to date.
[Inscryption Save File 9-25-23.zip](https://github.com/jlcrochet/inscryption_save_editor/files/12720997/Inscryption.Save.File.9-25-23.zip)

**Comment by jlcrochet** [comment]
Okay, this should be fixed now. Just let me know if there are any further problems.
