### ISSUE TITLE
Hey so after i decided to do a run with the waterborne deck which is now updated to start with the new kraken card and the part with Kaycee's mod just didn't show anything

### ISSUE THREAD

**Issue by Mariotron1** [jlcrochet/inscryption_save_editor#2]

**Comment by jlcrochet** [comment]
I did the same just now and didn't have any problems. If possible, could you attach your save file so that I can test it for myself?

**Comment by Mariotron1** [comment]
Ok here ya go........................................I would say if the file's format was y'know compatible.

**Comment by Mariotron1** [comment]
[SaveFile.zip](https://github.com/jlcrochet/inscryption_save_editor/files/8310497/SaveFile.zip)
Ok i here ya go

**Comment by Mariotron1** [comment]
> I did the same just now and didn't have any problems. If possible, could you attach your save file so that I can test it for myself?

Ok here it is i zipped up a copy of it because the file's format wasn't supported
[SaveFile.zip](https://github.com/jlcrochet/inscryption_save_editor/files/8310501/SaveFile.zip)

**Comment by jlcrochet** [comment]
Okay, I loaded your save file into the app and didn't see any issues. Could you be more specific about what the problem is? If you want to post a screenshot or something, that would work too.

**Comment by Mariotron1** [comment]
Ok also there are new cards added in Kaycee's mod
