### ISSUE TITLE
Error Parsing File

### ISSUE THREAD

**Issue by Vincent0690** [jlcrochet/inscryption_save_editor#20]
Hi, I loaded tried to load this file: 
[SaveFile.zip](https://github.com/jlcrochet/inscryption_save_editor/files/14812342/SaveFile.zip)
but got a Parsing error.

Thank you for making this tool, was working very well until this ❤️

**Comment by jlcrochet** [comment]
Hey, I think I fixed the problem. Give it another try once you get a chance and let me know how it goes.

**Comment by Vincent0690** [comment]
Works fine, thanks!
