### ISSUE TITLE
I cant edit my deck in Act 1

### ISSUE THREAD

**Issue by Rexasorous** [jlcrochet/inscryption_save_editor#21]
I haven't beaten the game, meaning my progression doesn't go past act 1 and when I try to edit my save file it doesn't seem to display anything when I press on the deck tab for act 1

**Comment by jlcrochet** [comment]
Can you send me a copy of your save file? You might have to put it in a .zip archive in order to post it here. Alternatively, you can e-mail it to me.

**Comment by Rexasorous** [comment]
this is the save file in question 
[Uploading SaveFile.gwsave.txt…]()
also the backup which hasnt been edited using your saveeditor
[Uploading SaveFile-Backup.gwsave.txt…]()

**Comment by Rexasorous** [comment]
w

**Comment by Rexasorous** [comment]
ignore that it didnt work ^ 
ill send an email

**Comment by Rexasorous** [comment]
hey justy started a new run and it seems to be fixed idk what was wrong thhough

**Comment by jlcrochet** [comment]
Okay. I didn't get a chance to look into it yet, so hopefully it's fixed now. Just let me know if it happens again.
