### ISSUE TITLE
It happened again the Kaycee's mod tab dissappeared again i think it's because i unlocked some new cards but i'm like 70% sure i'm wrong

### ISSUE THREAD

**Issue by Mariotron1** [jlcrochet/inscryption_save_editor#4]
Here's my save file 
[SaveFile (2).zip](https://github.com/jlcrochet/inscryption_save_editor/files/8319499/SaveFile.2.zip)

**Comment by Mariotron1** [comment]
Ok i unlocked the curious egg and now the kaycee's mod tab doesn't work

**Comment by jlcrochet** [comment]
Okay, I believe I've fixed the problem. Just let me know if it happens again.
