### ISSUE TITLE
Part One: Deck

### ISSUE THREAD

**Issue by iSupakilla** [jlcrochet/inscryption_save_editor#5]
The Deck section for Part One isn't loading. Everything else so far has been working great

**Comment by jlcrochet** [comment]
It's loading for me. If you don't mind, could you attach your save file so that I can test it?

**Comment by jlcrochet** [comment]
I think I've managed to fix this issue. If it happens again, please re-open this issue and attach your save file so that I can test it.

**Comment by iSupakilla** [comment]
Apologies on the late reply, I was doing a little hand editing and played a
few more rounds and checked when I got the email. It works now, whatever
changed. I know now at least
