### ISSUE TITLE
The Kaycee's mod tab isn't loading for some reason

### ISSUE THREAD

**Issue by Mariotron1** [jlcrochet/inscryption_save_editor#6]
Here's my save
[SaveFile (2).zip](https://github.com/jlcrochet/inscryption_save_editor/files/8368275/SaveFile.2.zip)

**Comment by jlcrochet** [comment]
I loaded that save file into the app and was able to get to the KMod tab just fine. Please try it again. If it still isn't showing up, please include a screenshot or something so that I can see what you're seeing.

**Comment by jlcrochet** [comment]
I think I've finally fixed this issue, so just let me know if it happesn again.
